server:
  port: 9527
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/traffic?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.douban.movie.model